### ISSUE TITLE
Exclude some element

### ISSUE THREAD

**Issue by Ganim** [chliebel/angular2-click-outside#2]
Hi, first I have to say... Thanks, thats a Amazing Plugin!!!

So... can you add a functionality to exclude some elements By ID? exemple.. The clickOutside Element is in the center of the page.. and want to exclude the Main Toolbar.. so when I click in anywhere less the clickOutsideElement and the Main Toolbar.. I get the action. Have a way to do this ?

**Comment by christianliebel** [comment]
Hi @Ganim, thanks for your feedback. The directive emits the `MouseEvent` passed to it:

`<my-element (clickOutside)="onClickOutside($event)"></my-element>`

In your `onClickOutside` function, you can examine the event and the target that has dispatched it (i.e. the element has been clicked on): https://developer.mozilla.org/en-US/docs/Web/API/Event/target

```
onClickOutside(event: MouseEvent) {
  // if (event.target.id === '') {
  // …
  // }
}
```

Here, you could check for the ID, attributes or any other prerequisites. I think this is preferable over a general solution provided by the directive.

Thanks again.

**Comment by christianliebel** [comment]
Hi @Ganim, as I haven’t heard back from you, I’d close this issue now. If you have any further questions, feel free to re-open it.
