### ISSUE TITLE
doesn't work with cli generated project

### ISSUE THREAD

**Issue by rob-balfre** [chliebel/angular2-click-outside#5]
Running Angular v4 generated by cli.  Directive is installed but does nothing, no error. Any ideas?

**Comment by iwannabaa** [comment]
@rob-balfre Did you sove this? I'm new to angular-cli and don't know how to add external directives

**Comment by rob-balfre** [comment]
Ended up not using it.

This is all you need mate.  Generate a directive using the CLI and then paste in this gist.
https://gist.github.com/rob-balfre/0c989ed6a4e131a09a684dabb649e0cd

**Comment by elliotaplant** [comment]
I found that this works for chrome with the ng cli, but not in firefox

**Comment by demiro** [comment]
@rob-balfre : well, your example works if I have only one of the kind...

in my case I have 3 dropdown components, all have the same clickOutside directive, but it gets triggered only when clicking anywhere outside of the dropdowns.... so if I have one open.... and click outside it gets triggered..... but if I have one open... and click on another.... it doesn't get triggered and both are now open

**Comment by fahdi** [comment]
@demiro I have the same exact issue with multiple dropdowns. Have been trying for a few hours now.

**Comment by ccdle12** [comment]
I'm not sure if it's the same issues outlined above by @demiro and @fahdi but the directive doesn't seem to like being applied to elements that are inside an *ngFor loop, specifically all clicks are registered as "outside clicks", anyone experienced this or have a work around?

**Comment by dhniels** [comment]
doesnt work on my non-CLI project.

**Comment by eitanfr** [comment]
it doent work because it bundled to SystemJs 
my work around is do to:
 `import { ClickOutsideDirective } from 'angular2-click-outside/clickOutside.directive';`

and adding the directive to your module declarations.

**Comment by dhniels** [comment]
That actually would probably solve it, but I ended up just using this one which seems to work. https://www.npmjs.com/package/ng-click-outside
